# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47c2860062f8928182b54bde812b4be839280e1bf0e906bbe5d0a3e9d9314647f827e9d5286bef4d2c506bffbcac5f6f728e06033bf46bae85e1a88ab188c83f

test:
  secret_key_base: 714da189ac0aff49f5e8719081059ff636978d1e9f3fed4862c641598d44eb474aebb0afdcad580f18297861dca0507746a9bc4b3990708c164241ff7fcd9de4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
